# Generated by Django 2.2.28 on 2024-04-30 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feeddata',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('run_value', models.CharField(max_length=20)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='leddata',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('led_number', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField(default=0)),
                ('shipping', models.IntegerField(default=0)),
                ('grandtotal', models.IntegerField(default=0)),
                ('customname', models.CharField(default='', max_length=100)),
                ('customemail', models.CharField(default='', max_length=100)),
                ('customaddress', models.CharField(default='', max_length=100)),
                ('customphone', models.CharField(default='', max_length=100)),
                ('paytype', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ph_states',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('PH', models.FloatField(blank=True, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='phdata',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('PH_value', models.CharField(max_length=20)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=100)),
                ('pprice', models.IntegerField(default=0)),
                ('pimages', models.CharField(default='', max_length=100)),
                ('pdescription', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='pumpdata',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('run_value', models.CharField(max_length=20)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Temperature', models.CharField(max_length=20)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=100)),
                ('unitprice', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('dtotal', models.IntegerField(default=0)),
                ('dorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.OrdersModel')),
            ],
        ),
    ]
